### PR TITLE
Chapter 6: Modeling Users

### PR DESCRIPTION
**Pull request by 1hoan234**
modeling users

### CODE REVIEW

**Comment by 1hoan234** [comment]
ready

**Comment by nhatnq-3267** [comment]
Merge pull chapter 3 r ready lại nhé

**Comment by 1hoan234** [comment]
> Merge pull chapter 3 r ready lại nhé

**Comment by 1hoan234** [comment]
ready

**Comment by 1hoan234** [comment]
ready

**Comment by 1hoan234** [comment]
ready

**Comment by 1hoan234** [comment]
ready

**Comment by nhatnq-3267** [comment]
merrged

**Pull request merged**
